"""Repack clear poses without blending; originals remain unchanged.

Run with E:/anaconda/envs/fastapi/python.exe market_frontend/scripts/build_auth_mascot_sprites.py.
"""
import json
import math
import re
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "public/generated/auth-partners"
POSES = (0, 2, 4, 6, 8, 10)
# Preserve the existing display scale, body pivot, and intentional flight heights.
SETTINGS = {
    "walk": (228.59, 84.6, (0, 1, 2, 3, 4, 5)),
    "run": (210.72, 106.9, (0, 1, 5)),
}


def main():
    metadata = {}
    for gait, (display_height, display_anchor, contacts) in SETTINGS.items():
        source = Image.open(ASSETS / f"mascot-{gait}.webp").convert("RGBA")
        cell = source.width / 12
        frame_width = math.ceil(cell)
        sheet = Image.new("RGBA", (frame_width * len(POSES), source.height))
        for index, pose in enumerate(POSES):
            frame = source.crop((round(pose * cell), 0,
                                 round((pose + 1) * cell), source.height))
            # Copy pixels exactly: no resizing, interpolation, or alpha blending.
            sheet.paste(frame, (index * frame_width, 0))
        filename = f"mascot-{gait}-clean.webp"
        sheet.save(ASSETS / filename, lossless=True, exact=True, method=6)
        metadata[gait] = {
            "src": f"/generated/auth-partners/{filename}",
            "frameCount": len(POSES), "frameWidth": frame_width,
            "frameHeight": source.height, "displayHeight": display_height,
            "anchorX": display_anchor * source.height / display_height,
            "offsetX": -7.7, "contactFrames": list(contacts),
        }
        print(f"{filename}: {sheet.width}x{sheet.height}, {len(POSES)} clear poses")
    target = ROOT / "src/generated/authMascotSprites.ts"
    target.parent.mkdir(parents=True, exist_ok=True)
    serialized = json.dumps(metadata, ensure_ascii=False, indent=2)
    serialized = re.sub(r'"(\w+)":', r'\1:', serialized)
    serialized = re.sub(
        r'contactFrames: \[([^\]]+)\]',
        lambda match: "contactFrames: [" + ", ".join(re.findall(r'\d+', match[1])) + "]",
        serialized,
    )
    target.write_text(
        "// Generated by scripts/build_auth_mascot_sprites.py. Do not edit.\n"
        "export const AUTH_MASCOT_SPRITES = "
        + serialized
        + " as const;\n", encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
