-- MySQL 时间字段迁移（一次性执行，适用于已经存在的数据库）
--
-- 目标：由 MySQL 统一负责 createTime / updateTime 的生成，避免应用层
-- 手动赋值或 MyBatis-Plus 更新时把旧时间重新写回数据库。
--
-- 执行前请完成数据库备份，并确认当前连接的数据库就是业务库。
-- ALTER TABLE 会隐式提交事务；建议在发布窗口执行。
-- 本脚本可以重复执行：补值 UPDATE 只处理 NULL，字段定义重复 MODIFY 不会改变数据。

-- 先补齐历史数据，确保后续 NOT NULL 约束可以安全生效。
UPDATE ai_agent_trace
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL;

UPDATE ai_conversation
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP),
    updateTime = COALESCE(updateTime, createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL
   OR updateTime IS NULL;

UPDATE ai_message
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP),
    updateTime = COALESCE(updateTime, createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL
   OR updateTime IS NULL;

UPDATE ai_usage_daily
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP),
    updateTime = COALESCE(updateTime, createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL
   OR updateTime IS NULL;

UPDATE ai_usage_global_daily
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP),
    updateTime = COALESCE(updateTime, createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL
   OR updateTime IS NULL;

UPDATE barrage
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP),
    updateTime = COALESCE(updateTime, createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL
   OR updateTime IS NULL;

UPDATE campus_coin_transaction
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL;

UPDATE comment
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP),
    updateTime = COALESCE(updateTime, createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL
   OR updateTime IS NULL;

UPDATE commodity
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP),
    updateTime = COALESCE(updateTime, createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL
   OR updateTime IS NULL;

UPDATE commodity_order
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP),
    updateTime = COALESCE(updateTime, createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL
   OR updateTime IS NULL;

UPDATE commodity_score
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP),
    updateTime = COALESCE(updateTime, createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL
   OR updateTime IS NULL;

UPDATE commodity_type
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP),
    updateTime = COALESCE(updateTime, createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL
   OR updateTime IS NULL;

UPDATE notice
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP),
    updateTime = COALESCE(updateTime, createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL
   OR updateTime IS NULL;

UPDATE post
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP),
    updateTime = COALESCE(updateTime, createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL
   OR updateTime IS NULL;

UPDATE post_favour
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP),
    updateTime = COALESCE(updateTime, createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL
   OR updateTime IS NULL;

UPDATE post_thumb
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP),
    updateTime = COALESCE(updateTime, createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL
   OR updateTime IS NULL;

UPDATE private_message
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP),
    updateTime = COALESCE(updateTime, createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL
   OR updateTime IS NULL;

UPDATE user
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP),
    updateTime = COALESCE(updateTime, createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL
   OR updateTime IS NULL;

UPDATE user_commodity_favorites
SET createTime = COALESCE(createTime, CURRENT_TIMESTAMP),
    updateTime = COALESCE(updateTime, createTime, CURRENT_TIMESTAMP)
WHERE createTime IS NULL
   OR updateTime IS NULL;

-- 统一字段定义。保留现有 camelCase 列名，避免影响 MyBatis 映射。
ALTER TABLE ai_agent_trace
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE ai_conversation
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE ai_message
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE ai_usage_daily
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE ai_usage_global_daily
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE barrage
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE campus_coin_transaction
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE comment
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE commodity
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE commodity_order
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE commodity_score
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE commodity_type
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE notice
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE post
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE post_favour
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE post_thumb
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE private_message
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE user
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE user_commodity_favorites
    MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
